# ============================================================
#  PROFILES CONFIG (Maxgear)
#  Множники, формати, валюта, структура колонок для кожного типу прайсу
#  Використовується для автоматичної генерації Excel/CSV файлів
# ============================================================

common:
  rounding:
    EUR: 2      # два знаки після коми
    UAH: 0      # цілі гривні

profiles:
  # ----------------- 1. NETTO (EUR) -----------------
  - name: netto_xlsx
    factor: 1.00
    currency_out: EUR
    format: xlsx
    r2_prefix: "netto/"
    columns:
      - { from: code,     header: "code" }
      - { from: unicode,  header: "unicode" }
      - { from: brand,    header: "brand" }
      - { from: name,     header: "name" }
      - { from: stock,    header: "stock" }
      - { from: price,    header: "price_EUR" }

  # ----------------- 2. 1.23 (EUR) -----------------
  - name: x1_23_xlsx
    factor: 1.23
    currency_out: EUR
    format: xlsx
    r2_prefix: "1_23/"
    columns:
      - { from: code,     header: "code" }
      - { from: unicode,  header: "unicode" }
      - { from: brand,    header: "brand" }
      - { from: name,     header: "name" }
      - { from: stock,    header: "stock" }
      - { from: price,    header: "price_EUR" }

  # ----------------- 3. 1.27 (EUR) -----------------
  - name: x1_27_xlsx
    factor: 1.27
    currency_out: EUR
    format: xlsx
    r2_prefix: "1_27/"
    columns:
      - { from: code,     header: "code" }
      - { from: unicode,  header: "unicode" }
      - { from: brand,    header: "brand" }
      - { from: name,     header: "name" }
      - { from: stock,    header: "stock" }
      - { from: price,    header: "price_EUR" }

  # ----------------- 4. EXIST 1.33 (UAH) -----------------
  - name: exist_1_33_xlsx
    factor: 1.33
    currency_out: UAH
    format: xlsx
    r2_prefix: "exist/1_33/"
    rate_policy: nbu_plus        # курс НБУ + надбавка
    rate_params:
      add_uah: 1                 # +1 грн до курсу НБУ
      min_rate: 49               # нижче не опускатись
      fallback: { policy: manual_fixed, value: 50 }  # якщо API недоступне
    columns:
      - { from: brand,  header: "brand" }
      - { from: code,   header: "code" }
      - { from: stock,  header: "stock" }
      - { from: price,  header: "price_UAH" }

  # ----------------- 5. SITE 1.33 (EUR, CSV) -----------------
  - name: site_1_33_csv
    factor: 1.33
    currency_out: EUR
    format: csv
    r2_prefix: "site/1_33/"
    csv:
      delimiter: ";"
      header: true
    columns:
      - { from: supplier_id, header: "supplier_id" }   # бере supplier_id з suppliers.yaml
      - { from: code,        header: "code" }
      - { from: unicode,     header: "unicode" }
      - { from: brand,       header: "brand" }
      - { from: name,        header: "name" }
      - { from: stock,       header: "stock" }
      - { from: price,       header: "price_EUR" }
