# ============================================================
# SUPPLIERS CONFIG
# Кожен постачальник описується блоком з мапінгом колонок.
# ============================================================

AP_GDANSK:
  supplier_id: 2

  # ----------------- Формат сирого CSV -----------------
  raw_layout:
    columns:
      code: 0         # SYMBOL
      unicode: 0      # дублюємо code
      brand: 1        # KLIENTA
      name: 1         # дублюємо brand
      stock: 3        # STAN
      price: 2        # CENA
    stock_index: 3
    stock_header_token: "STAN"
    gt5_to: 10

  # ----------------- Підказки читання CSV -----------------
  csv_hint:
    encoding: "utf-8"
    delimiter: ";"

  # ----------------- Попередня обробка -----------------
  preprocess:
    skip_rows: 1        # пропускаємо перший рядок із шапкою

  # ----------------- Нормалізація даних -----------------
  normalize:
    replace_gt_sign: true     # замінювати "> 5" на gt5_to
    trim_spaces: true         # обрізати пробіли
    replace_commas: true      # замінювати коми у цінах на крапки

  # ----------------- Примітки -----------------
  notes: >
    У постачальника AP_GDANSK стовпці:
    SYMBOL; CENA; KLIENTA; STAN.
    code = unicode, brand = name.
    STAN = stock, CENA = price.
    Перший рядок — заголовок, пропускається.


MOTOROL:
  supplier_id: 3
  raw_layout:
    columns:
      code: 0
      unicode: 1
      brand: 3
      name: 2
      stock: 4
      price: 5
    stock_index: 4
    stock_header_token: "stan"
    gt5_to: 10
  csv_hint:
    encoding: "utf-8"
    delimiter: ";"
  preprocess:
    skip_rows: 0
  normalize:
    mode: "csv"            # <-- ВАЖЛИВО: нічого не різати по пробілах
    replace_gt_sign: true  # '>5' -> 10


